sudo: false

language: python

python:
  - "pypy-5.4"
  - "pypy3.3-5.2-alpha1"
  - "nightly"
  - "3.6"
  - "3.5"
  - "3.4"
  - "3.3"
  - "2.7"
  - "2.6"
  
install:
  - pip install -U pytest
  - pip install msgpack-python
  - pip install coverage
  - pip install coveralls
  - pip install pytest-cov

before_script:
  - git clone https://github.com/msiemens/tinydb.git
  - cd tinydb
  - python setup.py install
  - cd ../tests
  - ./modifytests.sh
  - cd ..

script:
  py.test -v --cov tests

after_success:
  coveralls
